### ISSUE TITLE
The component Styled(icon) with the id has been created dynamically warnings

### ISSUE THREAD

**Issue by chorobin** [purple-technology/phoenix-components#180]
Getting warnings from ButtonIcon.tsx. This is probably because we're calling styled in the render method of ButtonIcon.tsx

 console.warn
      The component Styled(icon) with the id of "sc-igOmtu" has been created dynamically.
      You may see this warning because you've called styled inside another component.
      To resolve this only create new StyledComponents outside of any render method and function component.

**Comment by samuelg0rd0n** [comment]
Yeah, I know that we're doing that and I know that it's kinda anti-pattern but when I was creating the component I didn't know any other way. I'll take a look it again. Maybe there will be a better solution.

**Comment by chorobin** [comment]
Could we not move the styled out of the render call and use a dummy element like a div and then use the as prop?

https://styled-components.com/docs/api#as-polymorphic-prop

**Comment by samuelg0rd0n** [comment]
I'm not sure what you mean by that. Can you please give me an example?

Anyway, the whole point of this was to allow developers to use custom component BUT at the same time restrict this component to the correct size. Since the component is only available at the runtime, I can see no other solution than to wrap it in styled function inside our `ButtonIcon` component (current state).

However, I realised it's not working if the custom element doesn't propagate prop `className` to its root element anyway (because that's how styled-components work). Such as

```const CustomElement = ({ className }) => <svg className={className} /> ... </svg>```

Right now, AFAIK, this is only used in MyAxiory on two occasions, something like ```<Button icon={IoMdAddCircle} />``` and icons from `react-icons` correctly set `className` so it's working as it should.

I was thinking about giving up on the idea to restrict the size of this custom element and leave it completely up to the developer to use the correct size for different sizes of the Button. This way, we could use the component directly and we wouldn't need to used `styled` func at all.

Also, if we removed the `styled` func, I'd suggest changing custom `icon` prop type from `FunctionalComponent` to `ReactElement`. This way we'd write

```<Button icon={<IoMdAddCircle size="16px />} />``` instead of ```<Button icon={() => <IoMdAddCircle size="16px />} />```

The only reason it now accepts only `FunctionalComponent` is that `ReactElement` cannot be used with `styled`.

What do you think?

**Comment by chorobin** [comment]
I think passing the a custom icon is certainly a good idea. Maybe you're right about the size though, I think once you're passing the responsibility of to the user to provide a custom icon you could argue that they should size it appropriately.

**Comment by samuelg0rd0n** [comment]
I think you misunderstood the prop `as`. You cannot pass an element or component as you're doing in the example. You're passing `string`, such as `div`, `a` etc. In your case the element is `div` and you can write `as="a"` so it gets rendered as an anchor tag. Maybe I'm wrong but just by looking at this, I don't think it'll work.

In overall, I think we can pass the responsibility about the size to the user and get rid of the `styled`. And I'll change the type from `React.FC` to `ReactElement`. It feels more natural in my opinion.

**Comment by chorobin** [comment]
Should work as this is mentioned in the documentation
```
const Button = styled.button`
  display: inline-block;
  color: palevioletred;
  font-size: 1em;
  margin: 1em;
  padding: 0.25em 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;
  display: block;
`;

const ReversedButton = props => <Button {...props} children={props.children.split('').reverse()} />

render(
  <div>
    <Button>Normal Button</Button>
    <Button as={ReversedButton}>Custom Button with Normal Button styles</Button>
  </div>
);
```

**Comment by chorobin** [comment]
But yeah, maybe passing the size to the user is better and we can get rid of styled completely
